name: Format and lint

on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install yapf
        run: python -m pip install yapf
      - name: Format files
        run: yapf -ir .
